export type ModelId = (typeof models)[number]['id'];

const modelsData = {
	'google/gemini-2.5-flash': {
		provider: 'google',
		name: 'Gemini 2.5 Flash',
		id: 'google/gemini-2.5-flash',
		vision: true,
		webSearch: true,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'google/gemini-2.5-flash:thinking': {
		provider: 'google',
		name: 'Gemini 2.5 Flash (Thinking)',
		id: 'google/gemini-2.5-flash:thinking',
		vision: true,
		webSearch: true,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'google/gemini-2.5-pro': {
		provider: 'google',
		name: 'Gemini 2.5 Pro',
		id: 'google/gemini-2.5-pro',
		vision: true,
		webSearch: true,
		attachments: true,
		reasoning: true,
		fast: false,
		experimental: true,
	},
	'openai/o4-mini': {
		provider: 'openai',
		name: 'o4 mini',
		id: 'openai/o4-mini',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'anthropic/claude-sonnet-4': {
		provider: 'anthropic',
		name: 'Claude 4 Sonnet',
		id: 'anthropic/claude-sonnet-4',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'anthropic/claude-sonnet-4:reasoning': {
		provider: 'anthropic',
		name: 'Claude 4 Sonnet (Reasoning)',
		id: 'anthropic/claude-sonnet-4:reasoning',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'deepseek/deepseek-r1': {
		provider: 'deepseek',
		name: 'DeepSeek R1 (Llama Distilled)',
		id: 'deepseek/deepseek-r1',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'google/gemini-2.0-flash': {
		provider: 'google',
		name: 'Gemini 2.0 Flash',
		id: 'google/gemini-2.0-flash',
		vision: true,
		webSearch: true,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'google/gemini-2.0-flash-lite': {
		provider: 'google',
		name: 'Gemini 2.0 Flash Lite',
		id: 'google/gemini-2.0-flash-lite',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'openai/gpt-4o-mini': {
		provider: 'openai',
		name: 'GPT-4o mini',
		id: 'openai/gpt-4o-mini',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'openai/gpt-4o-2024-11-20': {
		provider: 'openai',
		name: 'GPT-4o',
		id: 'openai/gpt-4o-2024-11-20',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'openai/gpt-4.1': {
		provider: 'openai',
		name: 'GPT-4.1',
		id: 'openai/gpt-4.1',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'openai/gpt-4.1-mini': {
		provider: 'openai',
		name: 'GPT-4.1 Mini',
		id: 'openai/gpt-4.1-mini',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'openai/gpt-4.1-nano': {
		provider: 'openai',
		name: 'GPT-4.1 Nano',
		id: 'openai/gpt-4.1-nano',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'openai/o3-mini': {
		provider: 'openai',
		name: 'o3 mini',
		id: 'openai/o3-mini',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'openai/o3': {
		provider: 'openai',
		name: 'o3',
		id: 'openai/o3',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'openai/o3-pro': {
		provider: 'openai',
		name: 'o3 Pro',
		id: 'openai/o3-pro',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'anthropic/claude-3.5-sonnet-20240620': {
		provider: 'anthropic',
		name: 'Claude 3.5 Sonnet',
		id: 'anthropic/claude-3.5-sonnet-20240620',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'anthropic/claude-3.7-sonnet': {
		provider: 'anthropic',
		name: 'Claude 3.7 Sonnet',
		id: 'anthropic/claude-3.7-sonnet',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: false,
		fast: false,
		experimental: false,
	},
	'anthropic/claude-3.7-sonnet:thinking': {
		provider: 'anthropic',
		name: 'Claude 3.7 Sonnet (Reasoning)',
		id: 'anthropic/claude-3.7-sonnet:thinking',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'anthropic/claude-opus-4': {
		provider: 'anthropic',
		name: 'Claude 4 Opus',
		id: 'anthropic/claude-opus-4',
		vision: true,
		webSearch: false,
		attachments: true,
		reasoning: true,
		fast: false,
		experimental: false,
	},
	'meta-llama/llama-3.3-70b-instruct': {
		provider: 'meta',
		name: 'Llama 3.3 70b',
		id: 'meta-llama/llama-3.3-70b-instruct',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'meta-llama/llama-4-scout': {
		provider: 'meta',
		name: 'Llama 4 Scout',
		id: 'meta-llama/llama-4-scout',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'meta-llama/llama-4-maverick': {
		provider: 'meta',
		name: 'Llama 4 Maverick',
		id: 'meta-llama/llama-4-maverick',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'deepseek/deepseek-chat-v3-0324': {
		provider: 'deepseek',
		name: 'DeepSeek v3 (Fireworks)',
		id: 'deepseek/deepseek-chat-v3-0324',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'deepseek/deepseek-r1-0528': {
		provider: 'deepseek',
		name: 'DeepSeek R1 (0528)',
		id: 'deepseek/deepseek-r1-0528',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: true,
	},
	'deepseek/deepseek-r1:qwen-distilled': {
		provider: 'deepseek',
		name: 'DeepSeek R1 (Qwen Distilled)',
		id: 'deepseek/deepseek-r1:qwen-distilled',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: true,
	},
	'x-ai/grok-3-beta': {
		provider: 'xai',
		name: 'Grok 3',
		id: 'x-ai/grok-3-beta',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'x-ai/grok-3-mini-beta': {
		provider: 'xai',
		name: 'Grok 3 Mini',
		id: 'x-ai/grok-3-mini-beta',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: true,
	},
	'alibaba/qwen-qwa-32b': {
		provider: 'alibaba',
		name: 'Qwen qwq-32b',
		id: 'alibaba/qwen-qwa-32b',
		vision: false,
		webSearch: false,
		attachments: false,
		reasoning: true,
		fast: false,
		experimental: true,
	},
	'alibaba/qwen-2.5-32b': {
		provider: 'alibaba',
		name: 'Qwen 2.5 32b',
		id: 'alibaba/qwen-2.5-32b',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
	'openai/gpt-4.5-preview': {
		provider: 'openai',
		name: 'GPT-4.5',
		id: 'openai/gpt-4.5-preview',
		vision: true,
		webSearch: false,
		attachments: false,
		reasoning: false,
		fast: false,
		experimental: true,
	},
};

export const models = Object.values(modelsData).map((model) => ({
	name: model.name,
	id: model.id,
}));
